import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import Header from "@/components/Header";
import localFont from "next/font/local";
import { Pixelify_Sans } from "next/font/google";
import { cookies } from "next/headers";
import { ViewTransition } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pixelify = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-pixelify",
  weight: ["400", "600"],
});

const campton = localFont({
  src: [
    {
      path: "./fonts/CamptonLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/CamptonMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/CamptonBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/CamptonSemiBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-campton",
});

type LocaleCode = "fr" | "nl";

function normalizeLocale(rawLocale: string | undefined): LocaleCode {
  if (rawLocale === "nl") {
    return "nl";
  }
  return "fr";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const locale = normalizeLocale(cookieStore.get("locale")?.value);
  const messages = (await import(`../messages/${locale}.json`)).default;

  return (
    <html lang={locale}>
      <body className={` ${campton.variable} ${pixelify.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ViewTransition enter="slide-in">
            <Header />
            {children}
          </ViewTransition>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
