import type { Metadata } from 'next';
import './globals.css';
import { NextIntlClientProvider } from 'next-intl';
import Header from '@/components/Header';
import localFont from 'next/font/local';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
const campton = localFont({
	src: [
		{
			path: './fonts/CamptonLight.otf',
			weight: '300',
			style: 'normal',
		},
		{
			path: './fonts/CamptonMedium.otf',
			weight: '500',
			style: 'normal',
		},
		{
			path: './fonts/CamptonBold.otf',
			weight: '700',
			style: 'normal',
		},
		{
			path: './fonts/CamptonSemiBold.otf',
			weight: '800',
			style: 'normal',
		},
	],
	variable: '--font-campton',
});
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={` ${campton.variable} antialiased`}>
				<NextIntlClientProvider>
					<Header />
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
